// <auto-generated />
using EmartMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmartMvc.Migrations
{
    [DbContext(typeof(BuyerContext))]
    [Migration("20200130064529_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmartMvc.Models.Buyer", b =>
                {
                    b.Property<int>("B_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("B_createdatetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B_mobilenum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B_username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("B_id");

                    b.ToTable("Buyers");
                });
#pragma warning restore 612, 618
        }
    }
}
