// <auto-generated />
using EmartMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmartMvc.Migrations.Item
{
    [DbContext(typeof(ItemContext))]
    partial class ItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmartMvc.Models.Item", b =>
                {
                    b.Property<int>("I_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("C_id")
                        .HasColumnType("int");

                    b.Property<string>("I_des")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("I_price")
                        .HasColumnType("float");

                    b.Property<string>("I_remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("I_stocknum")
                        .HasColumnType("int");

                    b.Property<int>("SC_id")
                        .HasColumnType("int");

                    b.HasKey("I_id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
